default:

    port: 8000

    db:
        host: localhost
        port: 3306

        charset: UTF8_GENERAL_CI

    logfile: './main.log'



development:

    db:
        database: apiserver

        user: root
        password: password

        debug: true



production:

    db: # http://red.flydev.net/issues/5#note-3
        database: apiserver

        user: apiserver
        password: iamthe1337

        debug: false
