name: apiserver
version: 0.0.1



config:

    logfile: './main.log'
    pidfile: './main.pid'


    default:

        port: 8000

        db:
            host: 176.31.14.255
            port: 3306


    development:

        installed: false

        db:
            database: apiserver_dev

            user: apiserver
            password: iamthe1337

            debug: true


    production:

        installed: true

        db: # http://red.flydev.net/issues/5#note-3
            database: apiserver

            user: apiserver
            password: iamthe1337

            debug: false



scripts:
    start: node node.js



dependencies:

    extend: latest

    express: latest
    jade: latest

    passport: latest

    redis: latest
    mysql: latest

    log: latest
