name: apiserver
version: 0.0.1



config:
    logfile: './main.log'
    pidfile: './main.pid'


    default:

        port: 8000

        db:
            protocol: mysql
            host: office.kd-eurotrans.com
            port: 3306

            query:
                pool: true





    development:

        db:
            database: test

            user: test
            password: test

            query:
                debug: true



    production:

        db: # http://red.flydev.net/issues/5#note-3
            database: apiserver

            user: apiserver
            password: iamthe1337

            query:
                debug: false





scripts:
    start: node node.js



dependencies:

    extend: latest

    express: latest
    jade: latest

    passport: latest

    log: latest

    orm: latest
    mysql: latest
